# Generated by Django 3.2.6 on 2021-08-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_cartitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='resolution',
            field=models.CharField(choices=[('1mp', '1MP'), ('2mp', '2MP'), ('3mp', '3MP'), ('4mp', '4MP'), ('5mp', '5MP'), ('6mp', '6MP'), ('8mp', '7MP')], default='0', max_length=250),
        ),
    ]
