# Generated by Django 3.2.6 on 2021-08-29 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_resolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='corpus',
            field=models.CharField(choices=[('dome', 'Купольная'), ('bullet', 'Цилиндрическая')], default='0', max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='resolution',
            field=models.CharField(choices=[('1mp', '1MP'), ('2mp', '2MP'), ('3mp', '3MP'), ('4mp', '4MP'), ('5mp', '5MP'), ('6mp', '6MP'), ('8mp', '8MP')], default='0', max_length=250),
        ),
    ]
