# Generated by Django 3.2.6 on 2021-08-29 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20210829_0533'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('dome', 'Купольная'), ('bullet', 'Цилиндрическая'), ('ptz', 'Поворотная')], default='0', max_length=250),
        ),
        migrations.AddField(
            model_name='product',
            name='has_alarm_input',
            field=models.BooleanField(choices=[('yes', 'Есть'), ('no', 'Нет')], default='0'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_alarm_output',
            field=models.BooleanField(choices=[('yes', 'Есть'), ('no', 'Нет')], default='0'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_audio_input',
            field=models.BooleanField(choices=[('yes', 'Есть'), ('no', 'Нет')], default='0'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_audio_output',
            field=models.BooleanField(choices=[('yes', 'Есть'), ('no', 'Нет')], default='0'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_microsd',
            field=models.BooleanField(choices=[('yes', 'Есть'), ('no', 'Нет')], default='0'),
        ),
        migrations.AddField(
            model_name='product',
            name='has_wifi',
            field=models.BooleanField(choices=[('yes', 'Есть'), ('no', 'Нет')], default='0'),
        ),
        migrations.AddField(
            model_name='product',
            name='ik',
            field=models.CharField(choices=[('no', 'Нет'), ('10', '10'), ('15', '15'), ('20', '20'), ('30', '30'), ('40', '40'), ('50', '50'), ('60', '60'), ('70', '70'), ('80', '80'), ('100', '100')], default='0', max_length=250),
        ),
        migrations.AddField(
            model_name='product',
            name='protection',
            field=models.CharField(choices=[('no', 'Нет'), ('IP66', 'IP66'), ('IP67', 'IP67')], default='0', max_length=250),
        ),
        migrations.AddField(
            model_name='product',
            name='sensitivity',
            field=models.CharField(choices=[('0_01', '0.01л'), ('0_005', '0.005л'), ('0_0001', '0.0001лк')], default='0', max_length=250),
        ),
        migrations.AddField(
            model_name='product',
            name='sensor',
            field=models.CharField(choices=[('cmos1_2', 'CMOS 1/2"'), ('cmos1_25', 'CMOS 1/2.5"'), ('cmos1_27', 'CMOS 1/2.7"'), ('cmos1_28', 'CMOS 1/2.8"'), ('cmos1_29', 'CMOS 1/2.9"'), ('cmos1_3', 'CMOS 1/3"'), ('cmos1_4', 'CMOS 1/4"')], default='0', max_length=250),
        ),
        migrations.AddField(
            model_name='product',
            name='vand_protection',
            field=models.CharField(choices=[('no', 'Нет'), ('ik08', 'IK08'), ('ik10', 'IK10')], default='0', max_length=250),
        ),
        migrations.AddField(
            model_name='product',
            name='zoom',
            field=models.CharField(choices=[('no', '1MP'), ('4x', '4x'), ('10x', '10x'), ('15x', '15x'), ('20x', '20x'), ('23x', '23x'), ('25x', '25x')], default='0', max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='corpus',
            field=models.CharField(choices=[('dome', 'Купольная'), ('bullet', 'Цилиндрическая'), ('ptz', 'Поворотная')], default='0', max_length=250),
        ),
    ]
