# Generated by Django 3.2.6 on 2021-08-31 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20210829_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='camera_category',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='0', max_length=250),
        ),
        migrations.AddField(
            model_name='product',
            name='focal_length',
            field=models.CharField(choices=[('fixed', 'Фиксированный'), ('motorized', 'Моторизированный')], default='0', max_length=250),
        ),
        migrations.AddField(
            model_name='product',
            name='lens_type',
            field=models.CharField(choices=[('fixed', 'Фиксированный'), ('motorized', 'Моторизированный')], default='0', max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='has_alarm_input',
            field=models.BooleanField(choices=[(True, 'Есть'), (False, 'Нет')], default='0'),
        ),
        migrations.AlterField(
            model_name='product',
            name='has_alarm_output',
            field=models.BooleanField(choices=[(True, 'Есть'), (False, 'Нет')], default='0'),
        ),
        migrations.AlterField(
            model_name='product',
            name='has_audio_input',
            field=models.BooleanField(choices=[(True, 'Есть'), (False, 'Нет')], default='0'),
        ),
        migrations.AlterField(
            model_name='product',
            name='has_audio_output',
            field=models.BooleanField(choices=[(True, 'Есть'), (False, 'Нет')], default='0'),
        ),
        migrations.AlterField(
            model_name='product',
            name='has_microsd',
            field=models.BooleanField(choices=[(True, 'Есть'), (False, 'Нет')], default='0'),
        ),
        migrations.AlterField(
            model_name='product',
            name='has_wifi',
            field=models.BooleanField(choices=[(True, 'Есть'), (False, 'Нет')], default='0'),
        ),
        migrations.AlterField(
            model_name='product',
            name='zoom',
            field=models.CharField(choices=[('no', 'Нет'), ('4x', '4x'), ('10x', '10x'), ('15x', '15x'), ('20x', '20x'), ('23x', '23x'), ('25x', '25x')], default='0', max_length=250),
        ),
    ]
