# Generated by Django 3.2.6 on 2021-08-31 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_auto_20210831_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('dahua', 'Dahua'), ('hikvision', 'Hikvision'), ('hiwatch', 'HiWatch')], default='0', max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='sensitivity',
            field=models.CharField(default='0', max_length=250),
        ),
    ]
