# Generated by Django 3.2.6 on 2021-08-31 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20210831_1543'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='has_audio_input',
            new_name='has_micro',
        ),
        migrations.RemoveField(
            model_name='product',
            name='has_audio_output',
        ),
        migrations.AlterField(
            model_name='product',
            name='focal_length',
            field=models.CharField(choices=[('2mm', '2мм'), ('2.7-8.1mm', '2.7-8.1мм'), ('2.7-13.5mm', '2.7-13.5мм'), ('2.8mm', '2.8мм'), ('2.8-12mm', '2.8-12мм'), ('3.6mm', '3.6мм'), ('4.8-120mm', '4.8-120мм'), ('5-75mm', '5-75мм'), ('6mm', '6мм')], default='0', max_length=250),
        ),
    ]
