# Generated by Django 3.2.6 on 2021-09-01 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_auto_20210831_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_descr',
            field=models.CharField(blank=True, default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, choices=[('dahua', 'Dahua'), ('hikvision', 'Hikvision'), ('hiwatch', 'HiWatch')], default='0', max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='camera_category',
            field=models.CharField(blank=True, choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='0', max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='corpus',
            field=models.CharField(blank=True, choices=[('dome', 'Купольная'), ('bullet', 'Цилиндрическая'), ('ptz', 'Поворотная')], default='0', max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='focal_length',
            field=models.CharField(blank=True, choices=[('2mm', '2мм'), ('2.7-8.1mm', '2.7-8.1мм'), ('2.7-13.5mm', '2.7-13.5мм'), ('2.8mm', '2.8мм'), ('2.8-12mm', '2.8-12мм'), ('3.6mm', '3.6мм'), ('4.8-120mm', '4.8-120мм'), ('5-75mm', '5-75мм'), ('6mm', '6мм')], default='0', max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='has_micro',
            field=models.BooleanField(blank=True, choices=[(True, 'Есть'), (False, 'Нет')], default='0'),
        ),
        migrations.AlterField(
            model_name='product',
            name='has_microsd',
            field=models.BooleanField(blank=True, choices=[(True, 'Есть'), (False, 'Нет')], default='0'),
        ),
        migrations.AlterField(
            model_name='product',
            name='has_wifi',
            field=models.BooleanField(blank=True, choices=[(True, 'Есть'), (False, 'Нет')], default='0'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ik',
            field=models.CharField(blank=True, choices=[('no', 'Нет'), ('10', '10'), ('15', '15'), ('20', '20'), ('30', '30'), ('40', '40'), ('50', '50'), ('60', '60'), ('70', '70'), ('80', '80'), ('100', '100')], default='0', max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='lens_type',
            field=models.CharField(blank=True, choices=[('fixed', 'Фиксированный'), ('motorized', 'Моторизированный')], default='0', max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='protection',
            field=models.CharField(blank=True, choices=[('no', 'Нет'), ('IP66', 'IP66'), ('IP67', 'IP67')], default='0', max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='resolution',
            field=models.CharField(blank=True, choices=[('1mp', '1Мп'), ('2mp', '2Мп'), ('3mp', '3Мп'), ('4mp', '4Мп'), ('5mp', '5Мп'), ('6mp', '6Мп'), ('8mp', '8Мп')], default='0', max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='sensitivity',
            field=models.CharField(blank=True, default='0', max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='sensor',
            field=models.CharField(blank=True, choices=[('cmos1_2', 'CMOS 1/2"'), ('cmos1_25', 'CMOS 1/2.5"'), ('cmos1_27', 'CMOS 1/2.7"'), ('cmos1_28', 'CMOS 1/2.8"'), ('cmos1_29', 'CMOS 1/2.9"'), ('cmos1_3', 'CMOS 1/3"'), ('cmos1_4', 'CMOS 1/4"')], default='0', max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='zoom',
            field=models.CharField(blank=True, choices=[('no', 'Нет'), ('4x', '4x'), ('10x', '10x'), ('15x', '15x'), ('20x', '20x'), ('23x', '23x'), ('25x', '25x')], default='0', max_length=250),
        ),
    ]
